server:
  contextPath:  /kuier-clothes
  port: 8091


spring:
  datasource:
    url: jdbc:mysql://123.57.240.91:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1171623275Zz

mybatis:
  mapper-locations: classpath*:**/mapper/*Mapper.xml
  type-aliases-package: com.clothes.*.domain
# configuration:
#    cache-enabled: true